# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0P_RBwp7Osrby7SGM5wymCzKbFR6inQ
"""

import streamlit as st
from huggingface_hub import InferenceClient
from PyPDF2 import PdfReader

# Page config
st.set_page_config(page_title="AI Study Assistant", layout="centered")

st.title("📚 AI Study Assistant (Stable Version)")

# Load Hugging Face client (cached)
@st.cache_resource
def load_client():
    return InferenceClient(token=st.secrets["HF_TOKEN"])

client = load_client()

# File upload
uploaded_file = st.file_uploader("Upload PDF (optional)", type=["pdf"])

text_data = ""

# Extract PDF text
if uploaded_file:
    pdf = PdfReader(uploaded_file)
    for page in pdf.pages:
        extracted = page.extract_text()
        if extracted:
            text_data += extracted

# Manual input
manual_text = st.text_area("Or paste your notes here:")

if manual_text:
    text_data = manual_text

# Limit text size (prevents API overload)
text_data = text_data[:3000]

# Action selector
option = st.selectbox(
    "Choose Action",
    ["Ask Question", "Summarize", "Generate Quiz"]
)

# Function to call Hugging Face API
def generate_response(prompt):
    try:
        response = client.text_generation(
            prompt,
            model="google/flan-t5-base",
            max_new_tokens=200
        )
        return response
    except Exception as e:
        return f"❌ Error: {str(e)}"

# =========================
# ASK QUESTION
# =========================
if option == "Ask Question":
    query = st.text_input("Ask your question")

    if query:
        prompt = f"""Context:
{text_data}

Question: {query}

Answer clearly:"""

        with st.spinner("Thinking..."):
            response = generate_response(prompt)

        st.subheader("📌 Answer")
        st.write(response)

# =========================
# SUMMARIZE
# =========================
elif option == "Summarize":
    if st.button("Generate Summary"):
        if text_data.strip() == "":
            st.warning("Please upload or enter some text.")
        else:
            prompt = f"""Summarize the following content:

{text_data}
"""

            with st.spinner("Generating summary..."):
                response = generate_response(prompt)

            st.subheader("📄 Summary")
            st.write(response)

# =========================
# QUIZ GENERATOR
# =========================
elif option == "Generate Quiz":
    if st.button("Create Quiz"):
        if text_data.strip() == "":
            st.warning("Please upload or enter some text.")
        else:
            prompt = f"""From the following content:

{text_data}

Generate 5 quiz questions with answers.
"""

            with st.spinner("Creating quiz..."):
                response = generate_response(prompt)

            st.subheader("🧠 Quiz")
            st.write(response)